// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdProtoc.proto

package lanyotech.cn.park.protoc;

public final class AdProtoc {
  private AdProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(lanyotech.cn.park.protoc.AdProtoc.PullAdResponse.ads);
  }
  public interface AdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 id = 1;
    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string m_picture_name = 3;
    /**
     * <code>optional string m_picture_name = 3;</code>
     */
    boolean hasMPictureName();
    /**
     * <code>optional string m_picture_name = 3;</code>
     */
    java.lang.String getMPictureName();
    /**
     * <code>optional string m_picture_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getMPictureNameBytes();

    // optional string b_picture_name = 4;
    /**
     * <code>optional string b_picture_name = 4;</code>
     */
    boolean hasBPictureName();
    /**
     * <code>optional string b_picture_name = 4;</code>
     */
    java.lang.String getBPictureName();
    /**
     * <code>optional string b_picture_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getBPictureNameBytes();

    // optional string description = 5;
    /**
     * <code>optional string description = 5;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 5;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 5;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code protoc.Ad}
   *
   * <pre>
   *广告信息
   * </pre>
   */
  public static final class Ad extends
      com.google.protobuf.GeneratedMessage
      implements AdOrBuilder {
    // Use Ad.newBuilder() to construct.
    private Ad(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Ad(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Ad defaultInstance;
    public static Ad getDefaultInstance() {
      return defaultInstance;
    }

    public Ad getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Ad(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              mPictureName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              bPictureName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              description_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_Ad_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_Ad_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lanyotech.cn.park.protoc.AdProtoc.Ad.class, lanyotech.cn.park.protoc.AdProtoc.Ad.Builder.class);
    }

    public static com.google.protobuf.Parser<Ad> PARSER =
        new com.google.protobuf.AbstractParser<Ad>() {
      public Ad parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ad(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Ad> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string m_picture_name = 3;
    public static final int M_PICTURE_NAME_FIELD_NUMBER = 3;
    private java.lang.Object mPictureName_;
    /**
     * <code>optional string m_picture_name = 3;</code>
     */
    public boolean hasMPictureName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string m_picture_name = 3;</code>
     */
    public java.lang.String getMPictureName() {
      java.lang.Object ref = mPictureName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mPictureName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string m_picture_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMPictureNameBytes() {
      java.lang.Object ref = mPictureName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mPictureName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string b_picture_name = 4;
    public static final int B_PICTURE_NAME_FIELD_NUMBER = 4;
    private java.lang.Object bPictureName_;
    /**
     * <code>optional string b_picture_name = 4;</code>
     */
    public boolean hasBPictureName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string b_picture_name = 4;</code>
     */
    public java.lang.String getBPictureName() {
      java.lang.Object ref = bPictureName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bPictureName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string b_picture_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBPictureNameBytes() {
      java.lang.Object ref = bPictureName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bPictureName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string description = 5;
    public static final int DESCRIPTION_FIELD_NUMBER = 5;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 5;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string description = 5;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      name_ = "";
      mPictureName_ = "";
      bPictureName_ = "";
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMPictureNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getBPictureNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMPictureNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getBPictureNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.Ad parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lanyotech.cn.park.protoc.AdProtoc.Ad prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoc.Ad}
     *
     * <pre>
     *广告信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lanyotech.cn.park.protoc.AdProtoc.AdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_Ad_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_Ad_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lanyotech.cn.park.protoc.AdProtoc.Ad.class, lanyotech.cn.park.protoc.AdProtoc.Ad.Builder.class);
      }

      // Construct using protoc.AdProtoc.Ad.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        mPictureName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        bPictureName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_Ad_descriptor;
      }

      public lanyotech.cn.park.protoc.AdProtoc.Ad getDefaultInstanceForType() {
        return lanyotech.cn.park.protoc.AdProtoc.Ad.getDefaultInstance();
      }

      public lanyotech.cn.park.protoc.AdProtoc.Ad build() {
        lanyotech.cn.park.protoc.AdProtoc.Ad result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public lanyotech.cn.park.protoc.AdProtoc.Ad buildPartial() {
        lanyotech.cn.park.protoc.AdProtoc.Ad result = new lanyotech.cn.park.protoc.AdProtoc.Ad(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mPictureName_ = mPictureName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bPictureName_ = bPictureName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lanyotech.cn.park.protoc.AdProtoc.Ad) {
          return mergeFrom((lanyotech.cn.park.protoc.AdProtoc.Ad)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lanyotech.cn.park.protoc.AdProtoc.Ad other) {
        if (other == lanyotech.cn.park.protoc.AdProtoc.Ad.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMPictureName()) {
          bitField0_ |= 0x00000004;
          mPictureName_ = other.mPictureName_;
          onChanged();
        }
        if (other.hasBPictureName()) {
          bitField0_ |= 0x00000008;
          bPictureName_ = other.bPictureName_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000010;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lanyotech.cn.park.protoc.AdProtoc.Ad parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lanyotech.cn.park.protoc.AdProtoc.Ad) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 id = 1;
      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string m_picture_name = 3;
      private java.lang.Object mPictureName_ = "";
      /**
       * <code>optional string m_picture_name = 3;</code>
       */
      public boolean hasMPictureName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string m_picture_name = 3;</code>
       */
      public java.lang.String getMPictureName() {
        java.lang.Object ref = mPictureName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mPictureName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string m_picture_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMPictureNameBytes() {
        java.lang.Object ref = mPictureName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mPictureName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string m_picture_name = 3;</code>
       */
      public Builder setMPictureName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mPictureName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string m_picture_name = 3;</code>
       */
      public Builder clearMPictureName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mPictureName_ = getDefaultInstance().getMPictureName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string m_picture_name = 3;</code>
       */
      public Builder setMPictureNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mPictureName_ = value;
        onChanged();
        return this;
      }

      // optional string b_picture_name = 4;
      private java.lang.Object bPictureName_ = "";
      /**
       * <code>optional string b_picture_name = 4;</code>
       */
      public boolean hasBPictureName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string b_picture_name = 4;</code>
       */
      public java.lang.String getBPictureName() {
        java.lang.Object ref = bPictureName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bPictureName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string b_picture_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBPictureNameBytes() {
        java.lang.Object ref = bPictureName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bPictureName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string b_picture_name = 4;</code>
       */
      public Builder setBPictureName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bPictureName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string b_picture_name = 4;</code>
       */
      public Builder clearBPictureName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bPictureName_ = getDefaultInstance().getBPictureName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string b_picture_name = 4;</code>
       */
      public Builder setBPictureNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bPictureName_ = value;
        onChanged();
        return this;
      }

      // optional string description = 5;
      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 5;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string description = 5;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 5;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 5;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000010);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 5;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoc.Ad)
    }

    static {
      defaultInstance = new Ad(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoc.Ad)
  }

  public interface PullAdRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 longitude = 1;
    /**
     * <code>required int32 longitude = 1;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required int32 longitude = 1;</code>
     */
    int getLongitude();

    // required int32 latitude = 2;
    /**
     * <code>required int32 latitude = 2;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required int32 latitude = 2;</code>
     */
    int getLatitude();
  }
  /**
   * Protobuf type {@code protoc.PullAdRequest}
   *
   * <pre>
   *根据坐标点获取广告请求
   * </pre>
   */
  public static final class PullAdRequest extends
      com.google.protobuf.GeneratedMessage
      implements PullAdRequestOrBuilder {
    // Use PullAdRequest.newBuilder() to construct.
    private PullAdRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PullAdRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PullAdRequest defaultInstance;
    public static PullAdRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PullAdRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PullAdRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              longitude_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lanyotech.cn.park.protoc.AdProtoc.PullAdRequest.class, lanyotech.cn.park.protoc.AdProtoc.PullAdRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PullAdRequest> PARSER =
        new com.google.protobuf.AbstractParser<PullAdRequest>() {
      public PullAdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PullAdRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PullAdRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 longitude = 1;
    public static final int LONGITUDE_FIELD_NUMBER = 1;
    private int longitude_;
    /**
     * <code>required int32 longitude = 1;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 longitude = 1;</code>
     */
    public int getLongitude() {
      return longitude_;
    }

    // required int32 latitude = 2;
    public static final int LATITUDE_FIELD_NUMBER = 2;
    private int latitude_;
    /**
     * <code>required int32 latitude = 2;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 latitude = 2;</code>
     */
    public int getLatitude() {
      return latitude_;
    }

    private void initFields() {
      longitude_ = 0;
      latitude_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, latitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, latitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lanyotech.cn.park.protoc.AdProtoc.PullAdRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoc.PullAdRequest}
     *
     * <pre>
     *根据坐标点获取广告请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lanyotech.cn.park.protoc.AdProtoc.PullAdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lanyotech.cn.park.protoc.AdProtoc.PullAdRequest.class, lanyotech.cn.park.protoc.AdProtoc.PullAdRequest.Builder.class);
      }

      // Construct using protoc.AdProtoc.PullAdRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        longitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdRequest_descriptor;
      }

      public lanyotech.cn.park.protoc.AdProtoc.PullAdRequest getDefaultInstanceForType() {
        return lanyotech.cn.park.protoc.AdProtoc.PullAdRequest.getDefaultInstance();
      }

      public lanyotech.cn.park.protoc.AdProtoc.PullAdRequest build() {
        lanyotech.cn.park.protoc.AdProtoc.PullAdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public lanyotech.cn.park.protoc.AdProtoc.PullAdRequest buildPartial() {
        lanyotech.cn.park.protoc.AdProtoc.PullAdRequest result = new lanyotech.cn.park.protoc.AdProtoc.PullAdRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latitude_ = latitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lanyotech.cn.park.protoc.AdProtoc.PullAdRequest) {
          return mergeFrom((lanyotech.cn.park.protoc.AdProtoc.PullAdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lanyotech.cn.park.protoc.AdProtoc.PullAdRequest other) {
        if (other == lanyotech.cn.park.protoc.AdProtoc.PullAdRequest.getDefaultInstance()) return this;
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lanyotech.cn.park.protoc.AdProtoc.PullAdRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lanyotech.cn.park.protoc.AdProtoc.PullAdRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 longitude = 1;
      private int longitude_ ;
      /**
       * <code>required int32 longitude = 1;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 longitude = 1;</code>
       */
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <code>required int32 longitude = 1;</code>
       */
      public Builder setLongitude(int value) {
        bitField0_ |= 0x00000001;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 longitude = 1;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0;
        onChanged();
        return this;
      }

      // required int32 latitude = 2;
      private int latitude_ ;
      /**
       * <code>required int32 latitude = 2;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 latitude = 2;</code>
       */
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <code>required int32 latitude = 2;</code>
       */
      public Builder setLatitude(int value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 latitude = 2;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoc.PullAdRequest)
    }

    static {
      defaultInstance = new PullAdRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoc.PullAdRequest)
  }

  public interface PullAdResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protoc.PullAdResponse}
   *
   * <pre>
   *根据坐标点获取广告响应
   * </pre>
   */
  public static final class PullAdResponse extends
      com.google.protobuf.GeneratedMessage
      implements PullAdResponseOrBuilder {
    // Use PullAdResponse.newBuilder() to construct.
    private PullAdResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PullAdResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PullAdResponse defaultInstance;
    public static PullAdResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PullAdResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PullAdResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lanyotech.cn.park.protoc.AdProtoc.PullAdResponse.class, lanyotech.cn.park.protoc.AdProtoc.PullAdResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<PullAdResponse> PARSER =
        new com.google.protobuf.AbstractParser<PullAdResponse>() {
      public PullAdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PullAdResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PullAdResponse> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lanyotech.cn.park.protoc.AdProtoc.PullAdResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoc.PullAdResponse}
     *
     * <pre>
     *根据坐标点获取广告响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lanyotech.cn.park.protoc.AdProtoc.PullAdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lanyotech.cn.park.protoc.AdProtoc.PullAdResponse.class, lanyotech.cn.park.protoc.AdProtoc.PullAdResponse.Builder.class);
      }

      // Construct using protoc.AdProtoc.PullAdResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lanyotech.cn.park.protoc.AdProtoc.internal_static_protoc_PullAdResponse_descriptor;
      }

      public lanyotech.cn.park.protoc.AdProtoc.PullAdResponse getDefaultInstanceForType() {
        return lanyotech.cn.park.protoc.AdProtoc.PullAdResponse.getDefaultInstance();
      }

      public lanyotech.cn.park.protoc.AdProtoc.PullAdResponse build() {
        lanyotech.cn.park.protoc.AdProtoc.PullAdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public lanyotech.cn.park.protoc.AdProtoc.PullAdResponse buildPartial() {
        lanyotech.cn.park.protoc.AdProtoc.PullAdResponse result = new lanyotech.cn.park.protoc.AdProtoc.PullAdResponse(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lanyotech.cn.park.protoc.AdProtoc.PullAdResponse) {
          return mergeFrom((lanyotech.cn.park.protoc.AdProtoc.PullAdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lanyotech.cn.park.protoc.AdProtoc.PullAdResponse other) {
        if (other == lanyotech.cn.park.protoc.AdProtoc.PullAdResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lanyotech.cn.park.protoc.AdProtoc.PullAdResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lanyotech.cn.park.protoc.AdProtoc.PullAdResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoc.PullAdResponse)
    }

    static {
      defaultInstance = new PullAdResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoc.PullAdResponse)
    public static final int ADS_FIELD_NUMBER = 1501;
    /**
     * <code>extend .protoc.Response { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        lanyotech.cn.park.protoc.ResponseProtoc.Response,
        java.util.List<lanyotech.cn.park.protoc.AdProtoc.Ad>> ads = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          lanyotech.cn.park.protoc.AdProtoc.PullAdResponse.getDefaultInstance(),
          0,
          lanyotech.cn.park.protoc.AdProtoc.Ad.class,
          lanyotech.cn.park.protoc.AdProtoc.Ad.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoc_Ad_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoc_Ad_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoc_PullAdRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoc_PullAdRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoc_PullAdResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoc_PullAdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016AdProtoc.proto\022\006protoc\032\024ResponseProtoc" +
      ".proto\032\022CommonProtoc.proto\032\023AccountProto" +
      "c.proto\032\024MerchantProtoc.proto\"c\n\002Ad\022\n\n\002i" +
      "d\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\026\n\016m_picture_name\030" +
      "\003 \001(\t\022\026\n\016b_picture_name\030\004 \001(\t\022\023\n\013descrip" +
      "tion\030\005 \001(\t\"4\n\rPullAdRequest\022\021\n\tlongitude" +
      "\030\001 \002(\005\022\020\n\010latitude\030\002 \002(\005\"<\n\016PullAdRespon" +
      "se2*\n\003ads\022\020.protoc.Response\030\335\013 \003(\0132\n.pro" +
      "toc.AdB\010\n\006protoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoc_Ad_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoc_Ad_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoc_Ad_descriptor,
              new java.lang.String[] { "Id", "Name", "MPictureName", "BPictureName", "Description", });
          internal_static_protoc_PullAdRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protoc_PullAdRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoc_PullAdRequest_descriptor,
              new java.lang.String[] { "Longitude", "Latitude", });
          internal_static_protoc_PullAdResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protoc_PullAdResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoc_PullAdResponse_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lanyotech.cn.park.protoc.ResponseProtoc.getDescriptor(),
          lanyotech.cn.park.protoc.CommonProtoc.getDescriptor(),
          lanyotech.cn.park.protoc.AccountProtoc.getDescriptor(),
          lanyotech.cn.park.protoc.MerchantProtoc.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
