// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonProtoc.proto

package lanyotech.cn.park.protoc;

public final class CommonProtoc {
  private CommonProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code protoc.WEIBOENUM}
   *
   * <pre>
   *微博类型
   * </pre>
   */
  public enum WEIBOENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO = 0;</code>
     */
    NO(0, 0),
    /**
     * <code>SINA = 1;</code>
     */
    SINA(1, 1),
    /**
     * <code>TT = 2;</code>
     */
    TT(2, 2),
    ;

    /**
     * <code>NO = 0;</code>
     */
    public static final int NO_VALUE = 0;
    /**
     * <code>SINA = 1;</code>
     */
    public static final int SINA_VALUE = 1;
    /**
     * <code>TT = 2;</code>
     */
    public static final int TT_VALUE = 2;


    public final int getNumber() { return value; }

    public static WEIBOENUM valueOf(int value) {
      switch (value) {
        case 0: return NO;
        case 1: return SINA;
        case 2: return TT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WEIBOENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<WEIBOENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WEIBOENUM>() {
            public WEIBOENUM findValueByNumber(int number) {
              return WEIBOENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(0);
    }

    private static final WEIBOENUM[] VALUES = values();

    public static WEIBOENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private WEIBOENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoc.WEIBOENUM)
  }

  /**
   * Protobuf enum {@code protoc.PARKINGFREE}
   *
   * <pre>
   *停车位收费类型
   * </pre>
   */
  public enum PARKINGFREE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ALL = -1;</code>
     *
     * <pre>
     *所有
     * </pre>
     */
    ALL(0, -1),
    /**
     * <code>FREE = 0;</code>
     *
     * <pre>
     *免费
     * </pre>
     */
    FREE(1, 0),
    /**
     * <code>FEE_COUNT = 1;</code>
     *
     * <pre>
     *按次收费
     * </pre>
     */
    FEE_COUNT(2, 1),
    /**
     * <code>FEE_HOUR = 2;</code>
     *
     * <pre>
     *按时收费
     * </pre>
     */
    FEE_HOUR(3, 2),
    /**
     * <code>FEE_MONTH = 3;</code>
     *
     * <pre>
     *按月收费
     * </pre>
     */
    FEE_MONTH(4, 3),
    /**
     * <code>DISCOUNT = 4;</code>
     *
     * <pre>
     *限免
     * </pre>
     */
    DISCOUNT(5, 4),
    ;

    /**
     * <code>ALL = -1;</code>
     *
     * <pre>
     *所有
     * </pre>
     */
    public static final int ALL_VALUE = -1;
    /**
     * <code>FREE = 0;</code>
     *
     * <pre>
     *免费
     * </pre>
     */
    public static final int FREE_VALUE = 0;
    /**
     * <code>FEE_COUNT = 1;</code>
     *
     * <pre>
     *按次收费
     * </pre>
     */
    public static final int FEE_COUNT_VALUE = 1;
    /**
     * <code>FEE_HOUR = 2;</code>
     *
     * <pre>
     *按时收费
     * </pre>
     */
    public static final int FEE_HOUR_VALUE = 2;
    /**
     * <code>FEE_MONTH = 3;</code>
     *
     * <pre>
     *按月收费
     * </pre>
     */
    public static final int FEE_MONTH_VALUE = 3;
    /**
     * <code>DISCOUNT = 4;</code>
     *
     * <pre>
     *限免
     * </pre>
     */
    public static final int DISCOUNT_VALUE = 4;


    public final int getNumber() { return value; }

    public static PARKINGFREE valueOf(int value) {
      switch (value) {
        case -1: return ALL;
        case 0: return FREE;
        case 1: return FEE_COUNT;
        case 2: return FEE_HOUR;
        case 3: return FEE_MONTH;
        case 4: return DISCOUNT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PARKINGFREE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PARKINGFREE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PARKINGFREE>() {
            public PARKINGFREE findValueByNumber(int number) {
              return PARKINGFREE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(1);
    }

    private static final PARKINGFREE[] VALUES = values();

    public static PARKINGFREE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PARKINGFREE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoc.PARKINGFREE)
  }

  /**
   * Protobuf enum {@code protoc.VALIDSTATE}
   *
   * <pre>
   *停车位、商户验证状态
   * </pre>
   */
  public enum VALIDSTATE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNVERIFIED = 0;</code>
     *
     * <pre>
     *未验证
     * </pre>
     */
    UNVERIFIED(0, 0),
    /**
     * <code>NOPASS = 1;</code>
     *
     * <pre>
     *未通过验证
     * </pre>
     */
    NOPASS(1, 1),
    /**
     * <code>PASS = 2;</code>
     *
     * <pre>
     *通过验证
     * </pre>
     */
    PASS(2, 2),
    ;

    /**
     * <code>UNVERIFIED = 0;</code>
     *
     * <pre>
     *未验证
     * </pre>
     */
    public static final int UNVERIFIED_VALUE = 0;
    /**
     * <code>NOPASS = 1;</code>
     *
     * <pre>
     *未通过验证
     * </pre>
     */
    public static final int NOPASS_VALUE = 1;
    /**
     * <code>PASS = 2;</code>
     *
     * <pre>
     *通过验证
     * </pre>
     */
    public static final int PASS_VALUE = 2;


    public final int getNumber() { return value; }

    public static VALIDSTATE valueOf(int value) {
      switch (value) {
        case 0: return UNVERIFIED;
        case 1: return NOPASS;
        case 2: return PASS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VALIDSTATE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<VALIDSTATE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VALIDSTATE>() {
            public VALIDSTATE findValueByNumber(int number) {
              return VALIDSTATE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(2);
    }

    private static final VALIDSTATE[] VALUES = values();

    public static VALIDSTATE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private VALIDSTATE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoc.VALIDSTATE)
  }

  /**
   * Protobuf enum {@code protoc.PARKINGGENRE}
   *
   * <pre>
   *停车位类型
   * </pre>
   */
  public enum PARKINGGENRE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INDOOR = 1;</code>
     *
     * <pre>
     *室内
     * </pre>
     */
    INDOOR(0, 1),
    /**
     * <code>OUTDOOR = 2;</code>
     *
     * <pre>
     *室外
     * </pre>
     */
    OUTDOOR(1, 2),
    ;

    /**
     * <code>INDOOR = 1;</code>
     *
     * <pre>
     *室内
     * </pre>
     */
    public static final int INDOOR_VALUE = 1;
    /**
     * <code>OUTDOOR = 2;</code>
     *
     * <pre>
     *室外
     * </pre>
     */
    public static final int OUTDOOR_VALUE = 2;


    public final int getNumber() { return value; }

    public static PARKINGGENRE valueOf(int value) {
      switch (value) {
        case 1: return INDOOR;
        case 2: return OUTDOOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PARKINGGENRE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PARKINGGENRE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PARKINGGENRE>() {
            public PARKINGGENRE findValueByNumber(int number) {
              return PARKINGGENRE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(3);
    }

    private static final PARKINGGENRE[] VALUES = values();

    public static PARKINGGENRE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PARKINGGENRE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoc.PARKINGGENRE)
  }

  /**
   * Protobuf enum {@code protoc.PARKINGPICTURE}
   *
   * <pre>
   *停车位图片类型
   * </pre>
   */
  public enum PARKINGPICTURE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IN = 1;</code>
     *
     * <pre>
     *入口图片
     * </pre>
     */
    IN(0, 1),
    /**
     * <code>UNKOWN = 2;</code>
     *
     * <pre>
     *未知
     * </pre>
     */
    UNKOWN(1, 2),
    ;

    /**
     * <code>IN = 1;</code>
     *
     * <pre>
     *入口图片
     * </pre>
     */
    public static final int IN_VALUE = 1;
    /**
     * <code>UNKOWN = 2;</code>
     *
     * <pre>
     *未知
     * </pre>
     */
    public static final int UNKOWN_VALUE = 2;


    public final int getNumber() { return value; }

    public static PARKINGPICTURE valueOf(int value) {
      switch (value) {
        case 1: return IN;
        case 2: return UNKOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PARKINGPICTURE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PARKINGPICTURE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PARKINGPICTURE>() {
            public PARKINGPICTURE findValueByNumber(int number) {
              return PARKINGPICTURE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(4);
    }

    private static final PARKINGPICTURE[] VALUES = values();

    public static PARKINGPICTURE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PARKINGPICTURE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoc.PARKINGPICTURE)
  }

  /**
   * Protobuf enum {@code protoc.FEEDBACK4PARKING}
   *
   * <pre>
   *停车位“纠错”分类
   * </pre>
   */
  public enum FEEDBACK4PARKING
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_EXIST_PARKING = 1;</code>
     *
     * <pre>
     *停车场不存在
     * </pre>
     */
    NO_EXIST_PARKING(0, 1),
    /**
     * <code>PRICE_WRONG_PARKING = 2;</code>
     *
     * <pre>
     *价格错误
     * </pre>
     */
    PRICE_WRONG_PARKING(1, 2),
    /**
     * <code>LOCATION_WRONG_PARKING = 3;</code>
     *
     * <pre>
     *位置错误
     * </pre>
     */
    LOCATION_WRONG_PARKING(2, 3),
    /**
     * <code>OTHER_PARKING = 4;</code>
     *
     * <pre>
     *其他
     * </pre>
     */
    OTHER_PARKING(3, 4),
    ;

    /**
     * <code>NO_EXIST_PARKING = 1;</code>
     *
     * <pre>
     *停车场不存在
     * </pre>
     */
    public static final int NO_EXIST_PARKING_VALUE = 1;
    /**
     * <code>PRICE_WRONG_PARKING = 2;</code>
     *
     * <pre>
     *价格错误
     * </pre>
     */
    public static final int PRICE_WRONG_PARKING_VALUE = 2;
    /**
     * <code>LOCATION_WRONG_PARKING = 3;</code>
     *
     * <pre>
     *位置错误
     * </pre>
     */
    public static final int LOCATION_WRONG_PARKING_VALUE = 3;
    /**
     * <code>OTHER_PARKING = 4;</code>
     *
     * <pre>
     *其他
     * </pre>
     */
    public static final int OTHER_PARKING_VALUE = 4;


    public final int getNumber() { return value; }

    public static FEEDBACK4PARKING valueOf(int value) {
      switch (value) {
        case 1: return NO_EXIST_PARKING;
        case 2: return PRICE_WRONG_PARKING;
        case 3: return LOCATION_WRONG_PARKING;
        case 4: return OTHER_PARKING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FEEDBACK4PARKING>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FEEDBACK4PARKING>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FEEDBACK4PARKING>() {
            public FEEDBACK4PARKING findValueByNumber(int number) {
              return FEEDBACK4PARKING.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(5);
    }

    private static final FEEDBACK4PARKING[] VALUES = values();

    public static FEEDBACK4PARKING valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FEEDBACK4PARKING(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoc.FEEDBACK4PARKING)
  }

  /**
   * Protobuf enum {@code protoc.FEEDBACK4MERCHANT}
   *
   * <pre>
   *商户“纠错”分类
   * </pre>
   */
  public enum FEEDBACK4MERCHANT
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_EXIST_MERCHANT = 1;</code>
     *
     * <pre>
     *商户不存在
     * </pre>
     */
    NO_EXIST_MERCHANT(0, 1),
    /**
     * <code>INFO_WRONG_MERCHANT = 2;</code>
     *
     * <pre>
     *商户信息错误
     * </pre>
     */
    INFO_WRONG_MERCHANT(1, 2),
    /**
     * <code>LOCATION_WRONG_MERCHANT = 3;</code>
     *
     * <pre>
     *价格错误
     * </pre>
     */
    LOCATION_WRONG_MERCHANT(2, 3),
    /**
     * <code>OTHER_MERCHANT = 4;</code>
     *
     * <pre>
     *其他
     * </pre>
     */
    OTHER_MERCHANT(3, 4),
    ;

    /**
     * <code>NO_EXIST_MERCHANT = 1;</code>
     *
     * <pre>
     *商户不存在
     * </pre>
     */
    public static final int NO_EXIST_MERCHANT_VALUE = 1;
    /**
     * <code>INFO_WRONG_MERCHANT = 2;</code>
     *
     * <pre>
     *商户信息错误
     * </pre>
     */
    public static final int INFO_WRONG_MERCHANT_VALUE = 2;
    /**
     * <code>LOCATION_WRONG_MERCHANT = 3;</code>
     *
     * <pre>
     *价格错误
     * </pre>
     */
    public static final int LOCATION_WRONG_MERCHANT_VALUE = 3;
    /**
     * <code>OTHER_MERCHANT = 4;</code>
     *
     * <pre>
     *其他
     * </pre>
     */
    public static final int OTHER_MERCHANT_VALUE = 4;


    public final int getNumber() { return value; }

    public static FEEDBACK4MERCHANT valueOf(int value) {
      switch (value) {
        case 1: return NO_EXIST_MERCHANT;
        case 2: return INFO_WRONG_MERCHANT;
        case 3: return LOCATION_WRONG_MERCHANT;
        case 4: return OTHER_MERCHANT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FEEDBACK4MERCHANT>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FEEDBACK4MERCHANT>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FEEDBACK4MERCHANT>() {
            public FEEDBACK4MERCHANT findValueByNumber(int number) {
              return FEEDBACK4MERCHANT.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(6);
    }

    private static final FEEDBACK4MERCHANT[] VALUES = values();

    public static FEEDBACK4MERCHANT valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FEEDBACK4MERCHANT(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoc.FEEDBACK4MERCHANT)
  }

  /**
   * Protobuf enum {@code protoc.UGCENUM}
   *
   * <pre>
   *行为记录增加积分
   * </pre>
   */
  public enum UGCENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TO_DOWNLOAD_APP = 4;</code>
     *
     * <pre>
     *邀请好友下载
     * </pre>
     */
    TO_DOWNLOAD_APP(0, 4),
    /**
     * <code>TO_SHARE_WEIBO = 5;</code>
     *
     * <pre>
     *客户关分享微博
     * </pre>
     */
    TO_SHARE_WEIBO(1, 5),
    /**
     * <code>TO_FORWARD_DIANPING = 8;</code>
     *
     * <pre>
     *大众点评
     * </pre>
     */
    TO_FORWARD_DIANPING(2, 8),
    ;

    /**
     * <code>TO_DOWNLOAD_APP = 4;</code>
     *
     * <pre>
     *邀请好友下载
     * </pre>
     */
    public static final int TO_DOWNLOAD_APP_VALUE = 4;
    /**
     * <code>TO_SHARE_WEIBO = 5;</code>
     *
     * <pre>
     *客户关分享微博
     * </pre>
     */
    public static final int TO_SHARE_WEIBO_VALUE = 5;
    /**
     * <code>TO_FORWARD_DIANPING = 8;</code>
     *
     * <pre>
     *大众点评
     * </pre>
     */
    public static final int TO_FORWARD_DIANPING_VALUE = 8;


    public final int getNumber() { return value; }

    public static UGCENUM valueOf(int value) {
      switch (value) {
        case 4: return TO_DOWNLOAD_APP;
        case 5: return TO_SHARE_WEIBO;
        case 8: return TO_FORWARD_DIANPING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UGCENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<UGCENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UGCENUM>() {
            public UGCENUM findValueByNumber(int number) {
              return UGCENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(7);
    }

    private static final UGCENUM[] VALUES = values();

    public static UGCENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private UGCENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoc.UGCENUM)
  }

  public interface PageHelperOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 totalSize = 1;
    /**
     * <code>optional int32 totalSize = 1;</code>
     *
     * <pre>
     *查询返回总记录数
     * </pre>
     */
    boolean hasTotalSize();
    /**
     * <code>optional int32 totalSize = 1;</code>
     *
     * <pre>
     *查询返回总记录数
     * </pre>
     */
    int getTotalSize();

    // optional int32 pageIndex = 2 [default = 0];
    /**
     * <code>optional int32 pageIndex = 2 [default = 0];</code>
     *
     * <pre>
     *分页索引&lt;从0开始&gt;
     * </pre>
     */
    boolean hasPageIndex();
    /**
     * <code>optional int32 pageIndex = 2 [default = 0];</code>
     *
     * <pre>
     *分页索引&lt;从0开始&gt;
     * </pre>
     */
    int getPageIndex();

    // optional int32 count = 3 [default = 10];
    /**
     * <code>optional int32 count = 3 [default = 10];</code>
     *
     * <pre>
     *每页查询的条数
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 3 [default = 10];</code>
     *
     * <pre>
     *每页查询的条数
     * </pre>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code protoc.PageHelper}
   *
   * <pre>
   *分页
   * </pre>
   */
  public static final class PageHelper extends
      com.google.protobuf.GeneratedMessage
      implements PageHelperOrBuilder {
    // Use PageHelper.newBuilder() to construct.
    private PageHelper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PageHelper(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PageHelper defaultInstance;
    public static PageHelper getDefaultInstance() {
      return defaultInstance;
    }

    public PageHelper getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PageHelper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              totalSize_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageIndex_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_PageHelper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_PageHelper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lanyotech.cn.park.protoc.CommonProtoc.PageHelper.class, lanyotech.cn.park.protoc.CommonProtoc.PageHelper.Builder.class);
    }

    public static com.google.protobuf.Parser<PageHelper> PARSER =
        new com.google.protobuf.AbstractParser<PageHelper>() {
      public PageHelper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageHelper(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PageHelper> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 totalSize = 1;
    public static final int TOTALSIZE_FIELD_NUMBER = 1;
    private int totalSize_;
    /**
     * <code>optional int32 totalSize = 1;</code>
     *
     * <pre>
     *查询返回总记录数
     * </pre>
     */
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 totalSize = 1;</code>
     *
     * <pre>
     *查询返回总记录数
     * </pre>
     */
    public int getTotalSize() {
      return totalSize_;
    }

    // optional int32 pageIndex = 2 [default = 0];
    public static final int PAGEINDEX_FIELD_NUMBER = 2;
    private int pageIndex_;
    /**
     * <code>optional int32 pageIndex = 2 [default = 0];</code>
     *
     * <pre>
     *分页索引&lt;从0开始&gt;
     * </pre>
     */
    public boolean hasPageIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 pageIndex = 2 [default = 0];</code>
     *
     * <pre>
     *分页索引&lt;从0开始&gt;
     * </pre>
     */
    public int getPageIndex() {
      return pageIndex_;
    }

    // optional int32 count = 3 [default = 10];
    public static final int COUNT_FIELD_NUMBER = 3;
    private int count_;
    /**
     * <code>optional int32 count = 3 [default = 10];</code>
     *
     * <pre>
     *每页查询的条数
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 count = 3 [default = 10];</code>
     *
     * <pre>
     *每页查询的条数
     * </pre>
     */
    public int getCount() {
      return count_;
    }

    private void initFields() {
      totalSize_ = 0;
      pageIndex_ = 0;
      count_ = 10;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, totalSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pageIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, totalSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.PageHelper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lanyotech.cn.park.protoc.CommonProtoc.PageHelper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoc.PageHelper}
     *
     * <pre>
     *分页
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lanyotech.cn.park.protoc.CommonProtoc.PageHelperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_PageHelper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_PageHelper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lanyotech.cn.park.protoc.CommonProtoc.PageHelper.class, lanyotech.cn.park.protoc.CommonProtoc.PageHelper.Builder.class);
      }

      // Construct using protoc.CommonProtoc.PageHelper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        totalSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pageIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 10;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_PageHelper_descriptor;
      }

      public lanyotech.cn.park.protoc.CommonProtoc.PageHelper getDefaultInstanceForType() {
        return lanyotech.cn.park.protoc.CommonProtoc.PageHelper.getDefaultInstance();
      }

      public lanyotech.cn.park.protoc.CommonProtoc.PageHelper build() {
        lanyotech.cn.park.protoc.CommonProtoc.PageHelper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public lanyotech.cn.park.protoc.CommonProtoc.PageHelper buildPartial() {
        lanyotech.cn.park.protoc.CommonProtoc.PageHelper result = new lanyotech.cn.park.protoc.CommonProtoc.PageHelper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.totalSize_ = totalSize_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageIndex_ = pageIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lanyotech.cn.park.protoc.CommonProtoc.PageHelper) {
          return mergeFrom((lanyotech.cn.park.protoc.CommonProtoc.PageHelper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lanyotech.cn.park.protoc.CommonProtoc.PageHelper other) {
        if (other == lanyotech.cn.park.protoc.CommonProtoc.PageHelper.getDefaultInstance()) return this;
        if (other.hasTotalSize()) {
          setTotalSize(other.getTotalSize());
        }
        if (other.hasPageIndex()) {
          setPageIndex(other.getPageIndex());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lanyotech.cn.park.protoc.CommonProtoc.PageHelper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lanyotech.cn.park.protoc.CommonProtoc.PageHelper) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 totalSize = 1;
      private int totalSize_ ;
      /**
       * <code>optional int32 totalSize = 1;</code>
       *
       * <pre>
       *查询返回总记录数
       * </pre>
       */
      public boolean hasTotalSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 totalSize = 1;</code>
       *
       * <pre>
       *查询返回总记录数
       * </pre>
       */
      public int getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>optional int32 totalSize = 1;</code>
       *
       * <pre>
       *查询返回总记录数
       * </pre>
       */
      public Builder setTotalSize(int value) {
        bitField0_ |= 0x00000001;
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalSize = 1;</code>
       *
       * <pre>
       *查询返回总记录数
       * </pre>
       */
      public Builder clearTotalSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        totalSize_ = 0;
        onChanged();
        return this;
      }

      // optional int32 pageIndex = 2 [default = 0];
      private int pageIndex_ ;
      /**
       * <code>optional int32 pageIndex = 2 [default = 0];</code>
       *
       * <pre>
       *分页索引&lt;从0开始&gt;
       * </pre>
       */
      public boolean hasPageIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 pageIndex = 2 [default = 0];</code>
       *
       * <pre>
       *分页索引&lt;从0开始&gt;
       * </pre>
       */
      public int getPageIndex() {
        return pageIndex_;
      }
      /**
       * <code>optional int32 pageIndex = 2 [default = 0];</code>
       *
       * <pre>
       *分页索引&lt;从0开始&gt;
       * </pre>
       */
      public Builder setPageIndex(int value) {
        bitField0_ |= 0x00000002;
        pageIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pageIndex = 2 [default = 0];</code>
       *
       * <pre>
       *分页索引&lt;从0开始&gt;
       * </pre>
       */
      public Builder clearPageIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageIndex_ = 0;
        onChanged();
        return this;
      }

      // optional int32 count = 3 [default = 10];
      private int count_ = 10;
      /**
       * <code>optional int32 count = 3 [default = 10];</code>
       *
       * <pre>
       *每页查询的条数
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 count = 3 [default = 10];</code>
       *
       * <pre>
       *每页查询的条数
       * </pre>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 3 [default = 10];</code>
       *
       * <pre>
       *每页查询的条数
       * </pre>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000004;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 3 [default = 10];</code>
       *
       * <pre>
       *每页查询的条数
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        count_ = 10;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoc.PageHelper)
    }

    static {
      defaultInstance = new PageHelper(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoc.PageHelper)
  }

  public interface GpsPositionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 gpsPositionId = 1;
    /**
     * <code>optional int64 gpsPositionId = 1;</code>
     */
    boolean hasGpsPositionId();
    /**
     * <code>optional int64 gpsPositionId = 1;</code>
     */
    long getGpsPositionId();

    // optional int32 longitude = 2;
    /**
     * <code>optional int32 longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>optional int32 longitude = 2;</code>
     */
    int getLongitude();

    // optional int32 latitude = 3;
    /**
     * <code>optional int32 latitude = 3;</code>
     */
    boolean hasLatitude();
    /**
     * <code>optional int32 latitude = 3;</code>
     */
    int getLatitude();
  }
  /**
   * Protobuf type {@code protoc.GpsPosition}
   *
   * <pre>
   *坐标
   * </pre>
   */
  public static final class GpsPosition extends
      com.google.protobuf.GeneratedMessage
      implements GpsPositionOrBuilder {
    // Use GpsPosition.newBuilder() to construct.
    private GpsPosition(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GpsPosition(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GpsPosition defaultInstance;
    public static GpsPosition getDefaultInstance() {
      return defaultInstance;
    }

    public GpsPosition getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GpsPosition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gpsPositionId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              latitude_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_GpsPosition_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_GpsPosition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lanyotech.cn.park.protoc.CommonProtoc.GpsPosition.class, lanyotech.cn.park.protoc.CommonProtoc.GpsPosition.Builder.class);
    }

    public static com.google.protobuf.Parser<GpsPosition> PARSER =
        new com.google.protobuf.AbstractParser<GpsPosition>() {
      public GpsPosition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpsPosition(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GpsPosition> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 gpsPositionId = 1;
    public static final int GPSPOSITIONID_FIELD_NUMBER = 1;
    private long gpsPositionId_;
    /**
     * <code>optional int64 gpsPositionId = 1;</code>
     */
    public boolean hasGpsPositionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 gpsPositionId = 1;</code>
     */
    public long getGpsPositionId() {
      return gpsPositionId_;
    }

    // optional int32 longitude = 2;
    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private int longitude_;
    /**
     * <code>optional int32 longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 longitude = 2;</code>
     */
    public int getLongitude() {
      return longitude_;
    }

    // optional int32 latitude = 3;
    public static final int LATITUDE_FIELD_NUMBER = 3;
    private int latitude_;
    /**
     * <code>optional int32 latitude = 3;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 latitude = 3;</code>
     */
    public int getLatitude() {
      return latitude_;
    }

    private void initFields() {
      gpsPositionId_ = 0L;
      longitude_ = 0;
      latitude_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, gpsPositionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, latitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, gpsPositionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, latitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lanyotech.cn.park.protoc.CommonProtoc.GpsPosition prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoc.GpsPosition}
     *
     * <pre>
     *坐标
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lanyotech.cn.park.protoc.CommonProtoc.GpsPositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_GpsPosition_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_GpsPosition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lanyotech.cn.park.protoc.CommonProtoc.GpsPosition.class, lanyotech.cn.park.protoc.CommonProtoc.GpsPosition.Builder.class);
      }

      // Construct using protoc.CommonProtoc.GpsPosition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gpsPositionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lanyotech.cn.park.protoc.CommonProtoc.internal_static_protoc_GpsPosition_descriptor;
      }

      public lanyotech.cn.park.protoc.CommonProtoc.GpsPosition getDefaultInstanceForType() {
        return lanyotech.cn.park.protoc.CommonProtoc.GpsPosition.getDefaultInstance();
      }

      public lanyotech.cn.park.protoc.CommonProtoc.GpsPosition build() {
        lanyotech.cn.park.protoc.CommonProtoc.GpsPosition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public lanyotech.cn.park.protoc.CommonProtoc.GpsPosition buildPartial() {
        lanyotech.cn.park.protoc.CommonProtoc.GpsPosition result = new lanyotech.cn.park.protoc.CommonProtoc.GpsPosition(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gpsPositionId_ = gpsPositionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.latitude_ = latitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lanyotech.cn.park.protoc.CommonProtoc.GpsPosition) {
          return mergeFrom((lanyotech.cn.park.protoc.CommonProtoc.GpsPosition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lanyotech.cn.park.protoc.CommonProtoc.GpsPosition other) {
        if (other == lanyotech.cn.park.protoc.CommonProtoc.GpsPosition.getDefaultInstance()) return this;
        if (other.hasGpsPositionId()) {
          setGpsPositionId(other.getGpsPositionId());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lanyotech.cn.park.protoc.CommonProtoc.GpsPosition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lanyotech.cn.park.protoc.CommonProtoc.GpsPosition) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 gpsPositionId = 1;
      private long gpsPositionId_ ;
      /**
       * <code>optional int64 gpsPositionId = 1;</code>
       */
      public boolean hasGpsPositionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 gpsPositionId = 1;</code>
       */
      public long getGpsPositionId() {
        return gpsPositionId_;
      }
      /**
       * <code>optional int64 gpsPositionId = 1;</code>
       */
      public Builder setGpsPositionId(long value) {
        bitField0_ |= 0x00000001;
        gpsPositionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 gpsPositionId = 1;</code>
       */
      public Builder clearGpsPositionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gpsPositionId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 longitude = 2;
      private int longitude_ ;
      /**
       * <code>optional int32 longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 longitude = 2;</code>
       */
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional int32 longitude = 2;</code>
       */
      public Builder setLongitude(int value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0;
        onChanged();
        return this;
      }

      // optional int32 latitude = 3;
      private int latitude_ ;
      /**
       * <code>optional int32 latitude = 3;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 latitude = 3;</code>
       */
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional int32 latitude = 3;</code>
       */
      public Builder setLatitude(int value) {
        bitField0_ |= 0x00000004;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 latitude = 3;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoc.GpsPosition)
    }

    static {
      defaultInstance = new GpsPosition(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoc.GpsPosition)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoc_PageHelper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoc_PageHelper_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoc_GpsPosition_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoc_GpsPosition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CommonProtoc.proto\022\006protoc\032\024ResponsePr" +
      "otoc.proto\"H\n\nPageHelper\022\021\n\ttotalSize\030\001 " +
      "\001(\005\022\024\n\tpageIndex\030\002 \001(\005:\0010\022\021\n\005count\030\003 \001(\005" +
      ":\00210\"I\n\013GpsPosition\022\025\n\rgpsPositionId\030\001 \001" +
      "(\003\022\021\n\tlongitude\030\002 \001(\005\022\020\n\010latitude\030\003 \001(\005*" +
      "%\n\tWEIBOENUM\022\006\n\002NO\020\000\022\010\n\004SINA\020\001\022\006\n\002TT\020\002*c" +
      "\n\013PARKINGFREE\022\020\n\003ALL\020\377\377\377\377\377\377\377\377\377\001\022\010\n\004FREE\020" +
      "\000\022\r\n\tFEE_COUNT\020\001\022\014\n\010FEE_HOUR\020\002\022\r\n\tFEE_MO" +
      "NTH\020\003\022\014\n\010DISCOUNT\020\004*2\n\nVALIDSTATE\022\016\n\nUNV" +
      "ERIFIED\020\000\022\n\n\006NOPASS\020\001\022\010\n\004PASS\020\002*\'\n\014PARKI",
      "NGGENRE\022\n\n\006INDOOR\020\001\022\013\n\007OUTDOOR\020\002*$\n\016PARK" +
      "INGPICTURE\022\006\n\002IN\020\001\022\n\n\006UNKOWN\020\002*p\n\020FEEDBA" +
      "CK4PARKING\022\024\n\020NO_EXIST_PARKING\020\001\022\027\n\023PRIC" +
      "E_WRONG_PARKING\020\002\022\032\n\026LOCATION_WRONG_PARK" +
      "ING\020\003\022\021\n\rOTHER_PARKING\020\004*t\n\021FEEDBACK4MER" +
      "CHANT\022\025\n\021NO_EXIST_MERCHANT\020\001\022\027\n\023INFO_WRO" +
      "NG_MERCHANT\020\002\022\033\n\027LOCATION_WRONG_MERCHANT" +
      "\020\003\022\022\n\016OTHER_MERCHANT\020\004*K\n\007UGCENUM\022\023\n\017TO_" +
      "DOWNLOAD_APP\020\004\022\022\n\016TO_SHARE_WEIBO\020\005\022\027\n\023TO" +
      "_FORWARD_DIANPING\020\010B\010\n\006protoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoc_PageHelper_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoc_PageHelper_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoc_PageHelper_descriptor,
              new java.lang.String[] { "TotalSize", "PageIndex", "Count", });
          internal_static_protoc_GpsPosition_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protoc_GpsPosition_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoc_GpsPosition_descriptor,
              new java.lang.String[] { "GpsPositionId", "Longitude", "Latitude", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lanyotech.cn.park.protoc.ResponseProtoc.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
